#apiVersion: kubevirt.io/v1
#kind: VirtualMachine
- op: replace
  path: /metadata/labels/app
  value: prod-rhel9-vm
- op: replace
  path: /metadata/name
  value: prod-rhel9-vm
- op: replace
  path: spec/template/metadata/labels/kubevirt.io/domain
  value: prod-rhel9-vm
- op: replace
  path: spec/template/spec/domain/devices/disks/name
  value: prod-rhel9-vm-rootdisk
#  target:
#    kind: VirtualMachine
#    name: base-vm
#- patch: |-
#      - op: replace
#        path: spec/template/spec/domain/volumes/persistentVolumeClaim/claimName
#        value: new-rhel9-vm-rootdisk
#  target:
#    kind: VirtualMachine
#    name: base-vm
#- patch: |-
#      - op: replace
#        path: spec/template/spec/domain/volumes/name
#        value: new-rhel9-vm-rootdisk
#  target:
#    kind: VirtualMachine
#    name: base-vm
# resources:
# - ../../base