apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-vm-disk
  namespace: beehive-virtual-machines
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: base-vm-import-source
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
